//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsultasModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntoCarga
    {
        public int id { get; set; }
        public string tipo { get; set; }
        public Nullable<int> capMax { get; set; }
        public string fechaVenc { get; set; }
        public string direccionPunto { get; set; }
    
        public virtual Estacion Estacion { get; set; }
    }
}
